### ISSUE TITLE
Period and Single Quote characters not displayed correctly

### ISSUE THREAD

**Issue by JohnCMcDonough** [enquirer/readline-utils#3]
Periods and single quotes don't appear unless another key, that is not a period or single quote, is pressed. This issue appears to happen under node 8, 7, and 6, so it doesn't appear to be limited to the newer versions of node.

I tested using readline-utils@2.2.1 and prompt-base@3.0.5, which should be the latest versions for both. The code used to test was just the first bit of sample code found on the prompt-base Github's readme.

```
var Prompt = require('prompt-base');
var prompt = new Prompt({
  name: 'color',
  message: 'What is your favorite color?'
});

// promise
prompt.run()
  .then(function(answer) {
    console.log(answer);
    //=> 'blue'
  })
```

**Comment by jonschlinkert** [comment]
hmm, I don't think it's node. It's probably how keypresses are handled. we'll look into it, thanks for creating the issue.

edit: did you notice if double quotes worked? actually if it's convenient for you and you don't mind doing it, it would be great if you could try other wildcard/shift characters and let us know if you have issues with any others. I'll also check, but it's nice to have confirmation. thx

**Comment by JohnCMcDonough** [comment]
Yeah, I left out more information in the initial post. I'm using macOS 10.12.1, but it was also happening in a docker container running alpine linux. The terminal was the same though, everything was done using Apple's Terminal built into macOS.

**Comment by JohnCMcDonough** [comment]
Sorry, I missed your edit yesterday. The period and single quote were the only two that I found to be broken. Everything else appears to work fine.

**Comment by jonschlinkert** [comment]
hmm, maybe those are being lumped in with word characters. I'll look into it

edit: actually I'm not sure why they aren't emitting, but I suspect it's [this line](https://github.com/enquirer/readline-utils/blob/master/index.js#L602). I'll try to test it out as soon as I have a chance, or in the meantime, if you have a moment, try adding a dot and single quote to that string. If it works, feel free to do a pr or just comment back. thanks!

**Comment by doowb** [comment]
I tested this out and added the missing characters. I'll get this published after another fix gets merged in.
